spring.application.name=QuipuxProject

## Usuário e banco temporários apenas para o teste, em poucos dias será invalidado.
## Por esse motivo o link está sendo passado em hardcode e não em variavel de ambiente
spring.data.mongodb.uri=mongodb+srv://testUser:testUser@mongoparatestes.8euxnzj.mongodb.net/quipux_db?appName=mongoParaTestes